### ISSUE TITLE
error from callback at actual Beta 0.2.5b4

### ISSUE THREAD

**Issue by Rockhound53** [py-smart-gardena/hass-gardena-smart-system#100]
Hey Guys, 

i get an error with the gardena integration:

```
Logger: websocket
Source: /usr/local/lib/python3.9/site-packages/websocket/_logging.py:61
First occurred: 00:33:55 (8 occurrences)
Last logged: 05:33:54

error from callback <bound method Client.on_message of <gardena.smart_system.Client object at 0xffffa832c1f0>>: on_message() missing 1 required positional argument: 'message'
```

I hope its easy to fix? 

HA ist the aktual Version and the Integration is at 0.2.5b4

thanks for your helb and your nice work

**Comment by doabigcheese** [comment]
Hi,
i have the same issue and somewhere in a closed issue it was written that the library websocket-client is outdated...
i have HA installed on my raspberry pi, there "pip3 show websocket-client" showed Version 0.54.0
So did now an update to most recent version 1.3.2 with "pip3 install websocket-client --upgrade"
At least i have now in the log now error message any more from gardena smart system... lets see what the side effects will reveal... maybe some other stuff gets broken?
So what should be the ideal version to install ?

cheers,
doabigcheese

**Comment by tobiasbayer** [comment]
I have the same issue but I'm running Hassio. Thus, I cannot simply upgrade the websocket library.
Any suggestions?

**Comment by buentead** [comment]
I updated to version 0.2.5b4 and my water control and floor sensor works fine now (since 24 hours). I'm using the built-in websocket - no changes made here.

In case I'm running into unexpected troubles, I will report here.

This is my actual set up:
```
OS Version:               Home Assistant OS 7.6
Home Assistant Core:      2022.4.4
hass-gardena-smart-system 0.2.5b4
Board:                    rpi4-64
```

**Comment by grm** [comment]
The fact is that the underlying library (py-smart-gardena) is depending on a library which has a breaking change in one of its method interface.
That means, that depending on how the library was installed (it is a verry comon library), you may not have the correct version of the method which result in failure in the call.

The beta version is supporting the newer version of the library and the stable one is supporting the older version .. that was the quickest fix i had time to implement ! And i had not the time to create a matrix of the version of the library depending of the installation of home assistant to help users use which versions. ..

Regarding your issue, do not hesitate to tell me if you have still the issue or clise the ticket ? (it seems solved)

Btw, I am currently rewriting the whole library from nearly scratch in order to be able to maintein it more easily ... but it take me some time to do so ..

**Comment by grm** [comment]
You should update to latest beta !
it has its flaws, but it works better !

Please reopen a ticket if you still have an issue !
