### ISSUE TITLE
not able to log into gardena smart system

### ISSUE THREAD

**Issue by soesas** [py-smart-gardena/hass-gardena-smart-system#110]
Dear community,

I have problems logging into the Gardena smart system. I successfully installed it via HACS then I added it has an integration. When I first set up I need my email address, my password (both similar to the gardena app on Android)). And finally my API key. I never put in the API secret -  it's just the key the key is also confirmed as shown in the documentation. 
After I put in the information it just waits for a while and then resets the form to being empty again. 
When I look at the logs this is what it gives me

`Traceback (most recent call last):
  File "/config/custom_components/gardena_smart_system/config_flow.py", line 66, in async_step_user
    await self.hass.async_add_executor_job(
  File "/usr/local/lib/python3.9/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/gardena_smart_system/config_flow.py", line 133, in try_connection
    smart_system.update_locations()
  File "/usr/local/lib/python3.9/site-packages/gardena/smart_system.py", line 217, in update_locations
    response_data = self.__call_smart_system_get(f"{self.SMART_HOST}/v1/locations")
  File "/usr/local/lib/python3.9/site-packages/gardena/smart_system.py", line 188, in __call_smart_system_get
    if self.__response_has_errors(response):
  File "/usr/local/lib/python3.9/site-packages/gardena/smart_system.py", line 179, in __response_has_errors
    raise Exception(msg)
Exception: Forbidden (hint: did you 'Connect an API' in your Application?)`

I did double check the API seems to be correct. Email address and password as well as it is the same password as in the Android application

do you guys have any idea?

**Comment by bwentzel** [comment]
I experienced same issue. Please see last sentence in the traceback: "Exception: Forbidden (hint: did you 'Connect an API' in your Application?)"

You need to add the two API types to the application you created. ref step 5: Click on "+Connect new API" and connect the Authentication API and the GARDENA smart system API.

**Comment by soesas** [comment]
Ahh and then I add 2 APIs when configuring in jassistant? Or just the second one?

**Comment by bwentzel** [comment]
Add both Authentication API and the GARDENA smart system API. 
I got an error in Home Assistant after it was configured fine. Restarted and everything worked.

**Comment by soesas** [comment]
Thank you for the further tips. I'm now stuck at the Huskvarna developers app. I did create the API key with the API authentication app. do i have to further configure the configuration app within husqvarna developer_ it has a separate readme and swagger file and it seems awfully complicated to me. 
I originally thought I only put in the API key and that is set I actually have to do coding within the husqvarna application provided by Gardena or am I getting it all wrong?
So for being so complicated but I would really like to make it work.

**Comment by bwentzel** [comment]
This procedure worked for me few days ago:

1. Go to https://developer.husqvarnagroup.cloud/

2. Create an account if needed, otherwise sign in with your Gardena account.

3. After signing in you will be automatically redirected to "Your applications". (Otherwise go to: https://developer.husqvarnagroup.cloud/apps)

4. Create an new application by clicking "+ Create application", name it for example "My Home Assistant" (doesn't matter), leave the other fields empty including the Redirect URIs.
![step4](https://user-images.githubusercontent.com/23614532/166138648-86875196-9f39-4116-aa8a-c4ddc7439cce.png)

5. Click save on the new application and click on **"+Connect new API"** 
![Step5a](https://user-images.githubusercontent.com/23614532/166138659-41b332e7-a1ed-4ca4-8f51-47affb027984.png)
and first connect the **Authentication API**.  Then click on **"+Connect new API"** and also add the **GARDENA smart system API**. Click save once more.
![Step5b](https://user-images.githubusercontent.com/23614532/166138698-1a9d94e7-d889-4f1a-89fe-02b5fd2dbc33.png)

6. Now copy your Application Key, this is what you need when you add the integration in Home Assistant. Ignore the Application secret. You should see both of the API added to your application.
![Step6](https://user-images.githubusercontent.com/23614532/166138776-51688753-b390-42b8-801d-a58d6c1bef8b.png)

7. In Home Assistant, setup under Integrations, search for "Gardena Smart System". Then configure it with the Gardena user e-mail, password and the application key / client ID you copied in step 6. If you get some errors in Home Assistant, try to restart Home Assistant.

**Comment by soesas** [comment]
Oh boy I made it. It is now successfully connected thank you so much guys
