### ISSUE TITLE
new versions break the integration and beta gets offered as stable

### ISSUE THREAD

**Issue by riemers** [py-smart-gardena/hass-gardena-smart-system#129]
<img width="596" alt="image" src="https://user-images.githubusercontent.com/682041/179479398-7152624d-ee25-45b8-8fb9-a014f8a076e7.png">

This looks to me like beta versions, but they get offered by HACS. So you might need something in hacs config to tell those are beta.

As a side note, i tried it, failed i go this error. Maybe it is of use:

```
Logger: homeassistant.config_entries Source: custom_components/gardena_smart_system/__init__.py:45 Integration: Gardena Smart System integration ([documentation](https://github.com/py-smart-gardena/hass-gardena-smart-system), [issues](https://github.com/py-smart-gardena/hass-gardena-smart-system/issues)) First occurred: 10:58:59 AM (1 occurrences) Last logged: 10:58:59 AM
Error setting up entry for gardena_smart_system
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/config_entries.py", line 353, in async_setup
    result = await component.async_setup_entry(hass, self)
  File "/config/custom_components/gardena_smart_system/__init__.py", line 45, in async_setup_entry
    client_secret=entry.data[CONF_CLIENT_SECRET],
KeyError: 'client_secret'
```

**Comment by gijs007** [comment]
`Starting from version 1.0.0b5: You might probably have to uninstall and reinstall the integration as credentials requirements and method has changed. THERE IS A BREAKING CHANGE IN THE CONFIGURATION DUE TO AN UPDATE ON THE GARDENA API`
From the main page of the project.

Agreed that the version number looks like a beta. Can't find a changelog, hopefully this fixes the issue where the integration only pulls data at a restart of Home Assistant.

**Comment by riemers** [comment]
Ah yes so I see. I would expect this in the release notes on hacs too since you don’t read the repo’s main page of every project. I’ll try again and report if all is good.

**Comment by riemers** [comment]
So far it looks to be working, but indeed a full remove/install was needed. Found a change in the docs too, PR open for that. So far my moist sensor looks to be ok, water switch too and lawn mower.
