### ISSUE TITLE
Mower goes into "error" state when done mowing for the day

### ISSUE THREAD

**Issue by networkpotato** [py-smart-gardena/hass-gardena-smart-system#34]
When the mower is finished with the daily mowing schedule and goes into the dock to wait for the next time to start, the state of the entity in HA goes to `error`.

I am using an automation to alert me of actual errors (because the official Gardena app doesn't do this) and this works, when I for example lift the mower, it goes into the `error` state and alerts me.

But now it also alerts me every night when it's done mowing because it also then goes into the `error` state. 

This is a log of today's events. See how it starts to mow at 11, and goes back and forth to the dock to charge. When it's done for the day, the state of the entity (vacuum.xxx) goes to `error`, when the real state is `PARKED_DAILY_LIMIT_REACHED`:

![log](https://user-images.githubusercontent.com/32069841/85897038-cbabe000-b7f9-11ea-827e-3d508972f4f6.JPG)

![state](https://user-images.githubusercontent.com/32069841/85897040-cc447680-b7f9-11ea-8cc8-18f1a3c7dd9b.JPG)

**Comment by grm** [comment]
Hello,

That s a strange issue. According to the documentation 
PARKED_DAILY_LIMIT_REACHED - Mower has completed cutting due to daily limit reached

And indeed it is in errors ! I don t want to treat an error as if it is not, it is a really bad pattern ;)
Maybe the mower is running for too long and they set a hard limit regarding how many mowing cycles you can have per day. Did you change the duration of mowing when these erros starts to appear ?

Could you try to lower the mowing duration to see if the error disappears ?
In the meantime, i ll ask the dev if there is such a limit and why.

Also it would be great if you could add your automation template regarding errors alerting in the RECIPES.md and create a MR, sounds an interresting one other users could benefit from !

Thx,
Grm

**Comment by ludipq** [comment]
> Did you change the duration of mowing when these erros starts to appear ?
No, the schedule has been the same for 2 years now. Only one cycle, 11:00-21:00

> Also it would be great if you could add your automation template regarding errors alerting in the RECIPES.md and create a MR, sounds an interresting one other users could benefit from !
Sure, it's a really simple one though. But right now, seeing as the state goes to error when done for the day, it generates 1 false alarm a day.

**Comment by grm** [comment]
Ok I ll ask Gardena if there has been some changes.

Regarding the recipe, can you also give me your automation so I can check
if I don t have it on my side ?

Grm

**Comment by ludipq** [comment]
> Ok I ll ask Gardena if there has been some changes. Regarding the recipe, can you also give me your automation so I can check if I don t have it on my side

```
- id: '1592302100544'
  alias: MOWER - Notification of errors
  description: ''
  trigger:
  - entity_id: vacuum.mower
    platform: state
    to: error
  condition: []
  action:
  - data:
      message: An error has occured
      title: Mower
    service: notify.mobile_app_xxx_iphone
```

**Comment by ludipq** [comment]
It seems Gardena just released an update to their app. I now receive push notifications for the different error states.

So the problem in this Issue isn't fixed, but I (and probably no one else) won't need to use the `error` state for anything anymore.

**Comment by littletruckman** [comment]
Hello,

I am a new user of this integration and I experimented the same issue. Here are my findings if it helps:

1) The Error is in fact not an error: It is a warning that is issued once the mower is back at its dock after it worked for the maximum duration of the day (the one set in the Gardena account settings of the mower)
It sends the following WARNING message ("type":"MOWER"):

```
[gardena.smart_system] ------- Beginning of message ---------
[gardena.smart_system] {"id":"b64d07c2-735e-4309-aae5-ad357abf8bc0","type":"MOWER","attributes":{"state":{"value":"WARNING","timestamp":"2022-05-30T14:10:20.527+00:00"},"activity":{"value":"NONE","timestamp":"2022-05-30T14:10:20.527+00:00"},"lastErrorCode":{"value":"PARKED_DAILY_LIMIT_REACHED","timestamp":"2022-05-30T12:42:06.445+00:00"},"operatingHours":{"value":948}}}
[gardena.smart_system] ------- End of message ---------

```
In the code of the integration, it is handled as an error and the warning code PARKED_DAILY_LIMIT_REACHED is interpreted as an ERROR code.

2) Once docked, the mower sends on a regular basis "type":"COMMON" messages (charging)
```
[gardena.smart_system] ------- Beginning of message ---------
[gardena.smart_system] {"id":"b64d07c2-735e-4309-aae5-ad357abf8bc0","type":"COMMON","attributes":{"name":{"value":"JERRY"},"batteryLevel":{"value":50,"timestamp":"2022-05-30T13:54:33.556+00:00"},"batteryState":{"value":"CHARGING","timestamp":"2022-05-30T13:54:33.556+00:00"},"rfLinkLevel":{"value":100,"timestamp":"2022-05-30T13:29:40.399+00:00"},"serial":{"value":"200301894"},"modelType":{"value":"GARDENA smart Mower"},"rfLinkState":{"value":"ONLINE"}}}
[gardena.smart_system] ------- End of message ---------
```
As well as "type":"MOWER" messages:
```
[gardena.smart_system] ------- Beginning of message ---------
[gardena.smart_system] {"id":"b64d07c2-735e-4309-aae5-ad357abf8bc0","type":"MOWER","attributes":{"state":{"value":"WARNING","timestamp":"2022-05-30T14:10:20.527+00:00"},"activity":{"value":"NONE","timestamp":"2022-05-30T14:10:20.527+00:00"},"lastErrorCode":{"value":"PARKED_DAILY_LIMIT_REACHED","timestamp":"2022-05-30T12:42:06.445+00:00"},"operatingHours":{"value":949}}}
[gardena.smart_system] ------- End of message ---------

```

based on my logs, I tested a light change in the code (on my test installation), introducing differentiated handling for the WARNING in order to capture this specific STATE (See attached). It worked! Unfortunately, I have to redo it at every change in the integration.
The new History:
![image](https://user-images.githubusercontent.com/95052877/174473931-5873af9f-b873-46b3-9938-80f25e5043f1.png)


Could be an idea to integrate something similar in a future release (I am not a real developer :-) )
Also, missing adjustments in other files may be required!

Hope it helps
BR 

![Diff](https://user-images.githubusercontent.com/95052877/174473680-3e4d98a0-3505-4e90-b7a0-254ef354d1a1.jpg)

**Comment by Roedandan** [comment]
I know this is a real old thread, but this issue still seams to persist in version 0b109?

**Comment by Jogge** [comment]
> And indeed it is in errors ! I don t want to treat an error as if it is not, it is a really bad pattern ;)

@grm I disagree. It's not really an error. If it were an error, I would have to go to the lawnmower and fix the error, but in this case, I don't need to do anything other than wait until the next day.

How about changing the following:

https://github.com/py-smart-gardena/hass-gardena-smart-system/blob/957321918bdbedebfc6fb3942908810b86fa6754/custom_components/gardena_smart_system/vacuum.py#L96-L99

to:

```python
        if state in ["WARNING", "ERROR", "UNAVAILABLE"]:
            self._error_message = self._device.last_error_code
            if self._device.last_error_code == "PARKED_DAILY_LIMIT_REACHED":
                self._state = STATE_DOCKED
            else:
                _LOGGER.debug("Mower has an error")
                self._state = STATE_ERROR
```

Maybe it's even better to use `STATE_IDLE` instead of `STATE_DOCKED`?

**Comment by daveflanagan52** [comment]
+1 to this, I have this happen every so often, I don't get a notification from the official app for this state like I do the other errors
