### ISSUE TITLE
Sileno Bluetooth (minimo)

### ISSUE THREAD

**Issue by snickers2k** [py-smart-gardena/hass-gardena-smart-system#61]
Hey.
Is it possible to add the new Bluetooth Sileno models to this module? 
thanks

**Comment by fabian-pandas** [comment]
I'm also highly interested in Bluetooth support for sileno minimo models.

**Comment by grm** [comment]
Hello,

Hum, i do not own a sileno model like this one. Does it still needs the hub to work ? Or is it working only using a phone/computer by bluetooth ?

**Comment by simonlerpard** [comment]
My parents accidentally bought the bluetooth version. I tried to find work-arounds. And the best I could do seemed to be automating a phone to navigate the official bluetooth app. E.g. through testproject.io.

It's really not a good way, but at least it should work for some use cases.

We later tried to return it and buy the SMART version instead.

I don't think this project supports the bluetooth version, since it's a completely different integration. And you can't add a gateway to the bluetooth version (according to Gardena support).

**Comment by grm** [comment]
You are right, the bluetooth version does not seems to use the same app ( https://smart.gardena.com/#/session/new?username= ) ? or am i wrong ?

**Comment by grm** [comment]
I dont think we can adapt to this mower, sorry :(
