### ISSUE TITLE
Sensors Polling Values

### ISSUE THREAD

**Issue by Slam2** [py-smart-gardena/hass-gardena-smart-system#65]
Hello,

Do you think it's possible to apply the regular "Polling" of the Sensors's values ? The idea is to have the last values ​​of the Sensors during each _SCAN_INTERVAL_.

- If the Sensors updates it's value: It is reflected directly during the SCAN_INTERVAL.
- If the Sensors don't update it's value during the SCAN_INTERVAL period: The last known value is repeated.

The idea is to have regular historical values / for InfluxDB.

Thank you !
Slam2

**Comment by osks** [comment]
Perhaps the locations API can be polled and those values be reported. It's rate-limited though so can't poll that often. 

I'm strongly against reporting values that doesn't exist to Home Assistant, that I think would be really bad. They have to come from the API at the time they're reported. Otherwise one can never detect issues with the integration or connection since you still (made-up) data points coming in.

That doesn't mean I don't understand your problem. The humidity sensor values are very sparse and one missed value means it takes a long time before you get a new data point. I still think it would be much worse if older value was repeated. Even hourly polling would be an improvement. I'm not sure of what the rate-limit would allow, but I doubt every minute would work.

I think it's a good thing that when using InfluxDB with Home Assistant it doesn't lie about what have been measured. I recently switched from Prometheus to InfluxDB for the only reason that it only gets the actual measured values instead of repeated values when missing data.

**Comment by grm** [comment]
Hello,

we are not polling the API,but the API is sending us values whn there is. chage, and we store the updated value as the new state.
Also gardena is having  a limit of the number of calls we are doing per month, and having to poll the devices would make us hitting this limit very fast !

Jérémie
